name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  api-tests:
    name: API Tests
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm install
        
      - name: Run API tests
        run: npm run test:api
        
      - name: Upload API coverage
        uses: actions/upload-artifact@v4
        with:
          name: api-coverage
          path: backend/coverage/lcov.info
          retention-days: 30

  ui-tests:
    name: UI Tests
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm install
        
      - name: Install Playwright browsers
        run: npx playwright install --with-deps
        working-directory: ./frontend
        
      - name: Run UI tests
        run: npm run test:ui
        
      - name: Upload Playwright report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: ui-report
          path: frontend/playwright-report/
          retention-days: 30
